### ISSUE TITLE
Needs Logo

### ISSUE THREAD

**Issue by rzeigler** [rzeigler/waveguide#10]
Clearly, the project needs a swanky logo.

**Comment by mirzazulfan** [comment]
Hi @rzeigler I'm graphic designer and opensource enthusiast. I've designed a logo for you, what do you think? if you have an idea please share with me, it would be better for me. Best regard.
![waveguide](https://user-images.githubusercontent.com/36124339/57984058-ef8ee500-7a81-11e9-9d7a-4675803b1d04.png)

**Comment by rzeigler** [comment]
These look great. Thanks so much.

**Comment by mirzazulfan** [comment]
Thanks for your response, im glad you liked it. i'll sent all files and create a pr.

**Comment by mirzazulfan** [comment]
Hi @rzeigler i've created a pr #11 and you can download all editable files on the [drive](https://drive.google.com/drive/folders/1uUqbg2AzM2pjCDJ06tilJpTO4NnBe5io)
