### ISSUE TITLE
Environment parameter R

### ISSUE THREAD

**Issue by rzeigler** [rzeigler/waveguide#13]
Trifunctor here we come!

The core type would be `IO<R, E, A>` perhaps with interesting overloads with R fixed to some empty type and/or E set to never.

**Comment by ssledorze** [comment]
btw, it looks like another project, partially related to this one exists:

https://github.com/tusharmath/fearless-io

**Comment by sledorze** [comment]
Another related project

https://github.com/tusharmath/fearless-io

**Comment by rzeigler** [comment]
This it the final major API change I intend to go for before trying to stabilize the API for 1.0. The one thing that I have realized though is that the R and E parameters infect everything and make some of the actual type signatures potentially gnarly.

Ideally, an `IO<R1, E1, A>` should be able to unify with an `IO<R2, E2, A>` as `IO<R1, E1 | E2, A>` if R1 is a subtype of R2. This makes for potentially huge numbers of type parameters, especially in parts of the API where multiple error types can surface around the concurrency machinery. 

I suspect this will be a situation where I begin by roughing out the 3rd parameter and then gradually adding type machinery to account for the variance cases.

**Comment by rzeigler** [comment]
Some tinkering suggests that what is there is probably sufficient.
