### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by sledorze** [rzeigler/waveguide#5]
Even if tentative, it could help knowing what are your plans with waveguide.
If you want to implement some Abstractions, maybe, or not.

On top of my mind:
- Stream abstraction.
- Trifunctor (ala ZIO).

**Comment by rzeigler** [comment]
I think I will write something on the wiki when I have a few free moments. More fleshed out queues and a Stream are the next two things on my list along with some peripheral things (I'd like to do some wrappers around some browser and node apis for when I just want something straightforward).

**Comment by sledorze** [comment]
Back pressured?

**Comment by rzeigler** [comment]
That's part of the reason for wanting blocking and dropping queues so they can be used internally. My plan is backpressure stream along with queues to get push behavior for when it is warranted.

**Comment by sledorze** [comment]
Ok

**Comment by rzeigler** [comment]
[Roadmap](https://github.com/rzeigler/waveguide/wiki/Roadmap). Further bits to add to the roadmap can feature requests. I will leave this open until I create some milestones.

**Comment by sledorze** [comment]
Thanks, that's great to see the Roadmap.
